
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.swordverseonline.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.swordverseonline.item.WoodenSpearItem;
import net.mcreator.swordverseonline.item.WoodenRapierItem;
import net.mcreator.swordverseonline.item.WoodenMaceItem;
import net.mcreator.swordverseonline.item.WoodenHammerItem;
import net.mcreator.swordverseonline.item.WoodenDaggerItem;
import net.mcreator.swordverseonline.item.WoodenBattleAxeItem;
import net.mcreator.swordverseonline.item.WolfClawItem;
import net.mcreator.swordverseonline.item.UpgradeModSSSPlusItem;
import net.mcreator.swordverseonline.item.UpgradeModSSSItem;
import net.mcreator.swordverseonline.item.UpgradeModSSItem;
import net.mcreator.swordverseonline.item.UpgradeModSItem;
import net.mcreator.swordverseonline.item.UpgradeModCItem;
import net.mcreator.swordverseonline.item.UpgradeModBItem;
import net.mcreator.swordverseonline.item.UpgradeModAItem;
import net.mcreator.swordverseonline.item.TeleportCrystalItem;
import net.mcreator.swordverseonline.item.StoneSpearItem;
import net.mcreator.swordverseonline.item.StoneRapierItem;
import net.mcreator.swordverseonline.item.StoneMaceItem;
import net.mcreator.swordverseonline.item.StoneHammerItem;
import net.mcreator.swordverseonline.item.StoneDaggerItem;
import net.mcreator.swordverseonline.item.StoneBattleAxeItem;
import net.mcreator.swordverseonline.item.PointedStingerItem;
import net.mcreator.swordverseonline.item.NetheriteSpearItem;
import net.mcreator.swordverseonline.item.NetheriteRapierItem;
import net.mcreator.swordverseonline.item.NetheriteMaceItem;
import net.mcreator.swordverseonline.item.NetheriteHammerItem;
import net.mcreator.swordverseonline.item.NetheriteDaggerItem;
import net.mcreator.swordverseonline.item.NetheriteBattleAxeItem;
import net.mcreator.swordverseonline.item.IronSpearItem;
import net.mcreator.swordverseonline.item.IronRapierItem;
import net.mcreator.swordverseonline.item.IronMaceItem;
import net.mcreator.swordverseonline.item.IronHammerItem;
import net.mcreator.swordverseonline.item.IronDaggerItem;
import net.mcreator.swordverseonline.item.IronBattleAxeItem;
import net.mcreator.swordverseonline.item.HealingCrystalItem;
import net.mcreator.swordverseonline.item.GoldenSpearItem;
import net.mcreator.swordverseonline.item.GoldenRapierItem;
import net.mcreator.swordverseonline.item.GoldenMaceItem;
import net.mcreator.swordverseonline.item.GoldenHammerItem;
import net.mcreator.swordverseonline.item.GoldenDaggerItem;
import net.mcreator.swordverseonline.item.GoldenBattleAxeItem;
import net.mcreator.swordverseonline.item.ElucidatorItem;
import net.mcreator.swordverseonline.item.DiamondSpearItem;
import net.mcreator.swordverseonline.item.DiamondShardItem;
import net.mcreator.swordverseonline.item.DiamondRapierItem;
import net.mcreator.swordverseonline.item.DiamondMaceItem;
import net.mcreator.swordverseonline.item.DiamondHammerItem;
import net.mcreator.swordverseonline.item.DiamondDaggerItem;
import net.mcreator.swordverseonline.item.DiamondBattleAxeItem;
import net.mcreator.swordverseonline.item.DarkRepulserItem;
import net.mcreator.swordverseonline.item.CuringCrystalItem;
import net.mcreator.swordverseonline.item.BronzeSwordItem;
import net.mcreator.swordverseonline.item.BronzeRapierItem;
import net.mcreator.swordverseonline.item.BronzeNuggetItem;
import net.mcreator.swordverseonline.item.BronzeMaceItem;
import net.mcreator.swordverseonline.item.BronzeLanceItem;
import net.mcreator.swordverseonline.item.BronzeItem;
import net.mcreator.swordverseonline.item.BronzeIngotItem;
import net.mcreator.swordverseonline.item.BronzeDaggerItem;
import net.mcreator.swordverseonline.item.BronzeBattleAxeItem;
import net.mcreator.swordverseonline.item.BoarHideItem;
import net.mcreator.swordverseonline.SwordverseOnlineMod;

public class SwordverseOnlineModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, SwordverseOnlineMod.MODID);
	public static final RegistryObject<Item> HEALING_CRYSTAL = REGISTRY.register("healing_crystal", () -> new HealingCrystalItem());
	public static final RegistryObject<Item> CURING_CRYSTAL = REGISTRY.register("curing_crystal", () -> new CuringCrystalItem());
	public static final RegistryObject<Item> TELEPORT_CRYSTAL = REGISTRY.register("teleport_crystal", () -> new TeleportCrystalItem());
	public static final RegistryObject<Item> BLACKSMITH_SPAWN_EGG = REGISTRY.register("blacksmith_spawn_egg", () -> new ForgeSpawnEggItem(SwordverseOnlineModEntities.BLACKSMITH, -10079488, -6724096, new Item.Properties()));
	public static final RegistryObject<Item> BRONZE_INGOT = REGISTRY.register("bronze_ingot", () -> new BronzeIngotItem());
	public static final RegistryObject<Item> BRONZE_SWORD = REGISTRY.register("bronze_sword", () -> new BronzeSwordItem());
	public static final RegistryObject<Item> BRONZE_CHESTPLATE = REGISTRY.register("bronze_chestplate", () -> new BronzeItem.Chestplate());
	public static final RegistryObject<Item> BRONZE_LEGGINGS = REGISTRY.register("bronze_leggings", () -> new BronzeItem.Leggings());
	public static final RegistryObject<Item> BRONZE_BOOTS = REGISTRY.register("bronze_boots", () -> new BronzeItem.Boots());
	public static final RegistryObject<Item> BRONZE_RAPIER = REGISTRY.register("bronze_rapier", () -> new BronzeRapierItem());
	public static final RegistryObject<Item> BRONZE_DAGGER = REGISTRY.register("bronze_dagger", () -> new BronzeDaggerItem());
	public static final RegistryObject<Item> BRONZE_LANCE = REGISTRY.register("bronze_lance", () -> new BronzeLanceItem());
	public static final RegistryObject<Item> BRONZE_BATTLE_AXE = REGISTRY.register("bronze_battle_axe", () -> new BronzeBattleAxeItem());
	public static final RegistryObject<Item> IRON_BATTLE_AXE = REGISTRY.register("iron_battle_axe", () -> new IronBattleAxeItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronSpearItem());
	public static final RegistryObject<Item> IRON_RAPIER = REGISTRY.register("iron_rapier", () -> new IronRapierItem());
	public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new IronDaggerItem());
	public static final RegistryObject<Item> NETHERITE_BATTLE_AXE = REGISTRY.register("netherite_battle_axe", () -> new NetheriteBattleAxeItem());
	public static final RegistryObject<Item> NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", () -> new NetheriteDaggerItem());
	public static final RegistryObject<Item> NETHERITE_RAPIER = REGISTRY.register("netherite_rapier", () -> new NetheriteRapierItem());
	public static final RegistryObject<Item> NETHERITE_SPEAR = REGISTRY.register("netherite_spear", () -> new NetheriteSpearItem());
	public static final RegistryObject<Item> GOLDEN_BATTLE_AXE = REGISTRY.register("golden_battle_axe", () -> new GoldenBattleAxeItem());
	public static final RegistryObject<Item> STONE_BATTLE_AXE = REGISTRY.register("stone_battle_axe", () -> new StoneBattleAxeItem());
	public static final RegistryObject<Item> WOODEN_BATTLE_AXE = REGISTRY.register("wooden_battle_axe", () -> new WoodenBattleAxeItem());
	public static final RegistryObject<Item> GOLDEN_SPEAR = REGISTRY.register("golden_spear", () -> new GoldenSpearItem());
	public static final RegistryObject<Item> DIAMOND_SPEAR = REGISTRY.register("diamond_spear", () -> new DiamondSpearItem());
	public static final RegistryObject<Item> STONE_SPEAR = REGISTRY.register("stone_spear", () -> new StoneSpearItem());
	public static final RegistryObject<Item> WOODEN_SPEAR = REGISTRY.register("wooden_spear", () -> new WoodenSpearItem());
	public static final RegistryObject<Item> GOLDEN_DAGGER = REGISTRY.register("golden_dagger", () -> new GoldenDaggerItem());
	public static final RegistryObject<Item> DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", () -> new DiamondDaggerItem());
	public static final RegistryObject<Item> STONE_DAGGER = REGISTRY.register("stone_dagger", () -> new StoneDaggerItem());
	public static final RegistryObject<Item> WOODEN_DAGGER = REGISTRY.register("wooden_dagger", () -> new WoodenDaggerItem());
	public static final RegistryObject<Item> DIAMOND_RAPIER = REGISTRY.register("diamond_rapier", () -> new DiamondRapierItem());
	public static final RegistryObject<Item> GOLDEN_RAPIER = REGISTRY.register("golden_rapier", () -> new GoldenRapierItem());
	public static final RegistryObject<Item> DIAMOND_BATTLE_AXE = REGISTRY.register("diamond_battle_axe", () -> new DiamondBattleAxeItem());
	public static final RegistryObject<Item> STONE_RAPIER = REGISTRY.register("stone_rapier", () -> new StoneRapierItem());
	public static final RegistryObject<Item> WOODEN_RAPIER = REGISTRY.register("wooden_rapier", () -> new WoodenRapierItem());
	public static final RegistryObject<Item> BRONZE_NUGGET = REGISTRY.register("bronze_nugget", () -> new BronzeNuggetItem());
	public static final RegistryObject<Item> DIAMOND_SHARD = REGISTRY.register("diamond_shard", () -> new DiamondShardItem());
	public static final RegistryObject<Item> DIAMOND_MACE = REGISTRY.register("diamond_mace", () -> new DiamondMaceItem());
	public static final RegistryObject<Item> GOLDEN_MACE = REGISTRY.register("golden_mace", () -> new GoldenMaceItem());
	public static final RegistryObject<Item> IRON_MACE = REGISTRY.register("iron_mace", () -> new IronMaceItem());
	public static final RegistryObject<Item> STONE_MACE = REGISTRY.register("stone_mace", () -> new StoneMaceItem());
	public static final RegistryObject<Item> WOODEN_MACE = REGISTRY.register("wooden_mace", () -> new WoodenMaceItem());
	public static final RegistryObject<Item> NETHERITE_MACE = REGISTRY.register("netherite_mace", () -> new NetheriteMaceItem());
	public static final RegistryObject<Item> BRONZE_MACE = REGISTRY.register("bronze_mace", () -> new BronzeMaceItem());
	public static final RegistryObject<Item> UPGRADE_MOD_B = REGISTRY.register("upgrade_mod_b", () -> new UpgradeModBItem());
	public static final RegistryObject<Item> UPGRADE_MOD_A = REGISTRY.register("upgrade_mod_a", () -> new UpgradeModAItem());
	public static final RegistryObject<Item> UPGRADE_MOD_S = REGISTRY.register("upgrade_mod_s", () -> new UpgradeModSItem());
	public static final RegistryObject<Item> UPGRADE_MOD_SS = REGISTRY.register("upgrade_mod_ss", () -> new UpgradeModSSItem());
	public static final RegistryObject<Item> UPGRADE_MOD_SSS = REGISTRY.register("upgrade_mod_sss", () -> new UpgradeModSSSItem());
	public static final RegistryObject<Item> UPGRADE_MOD_SSS_PLUS = REGISTRY.register("upgrade_mod_sss_plus", () -> new UpgradeModSSSPlusItem());
	public static final RegistryObject<Item> WOODEN_HAMMER = REGISTRY.register("wooden_hammer", () -> new WoodenHammerItem());
	public static final RegistryObject<Item> STONE_HAMMER = REGISTRY.register("stone_hammer", () -> new StoneHammerItem());
	public static final RegistryObject<Item> IRON_HAMMER = REGISTRY.register("iron_hammer", () -> new IronHammerItem());
	public static final RegistryObject<Item> GOLDEN_HAMMER = REGISTRY.register("golden_hammer", () -> new GoldenHammerItem());
	public static final RegistryObject<Item> DIAMOND_HAMMER = REGISTRY.register("diamond_hammer", () -> new DiamondHammerItem());
	public static final RegistryObject<Item> NETHERITE_HAMMER = REGISTRY.register("netherite_hammer", () -> new NetheriteHammerItem());
	public static final RegistryObject<Item> WOLF_CLAW = REGISTRY.register("wolf_claw", () -> new WolfClawItem());
	public static final RegistryObject<Item> BOAR_HIDE = REGISTRY.register("boar_hide", () -> new BoarHideItem());
	public static final RegistryObject<Item> POINTED_STINGER = REGISTRY.register("pointed_stinger", () -> new PointedStingerItem());
	public static final RegistryObject<Item> UPGRADE_MOD_C = REGISTRY.register("upgrade_mod_c", () -> new UpgradeModCItem());
	public static final RegistryObject<Item> BRONZE_BLOCK = block(SwordverseOnlineModBlocks.BRONZE_BLOCK);
	public static final RegistryObject<Item> ELUCIDATOR = REGISTRY.register("elucidator", () -> new ElucidatorItem());
	public static final RegistryObject<Item> DARK_REPULSER = REGISTRY.register("dark_repulser", () -> new DarkRepulserItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
